name: SonarQube Scan

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the analysis on

jobs:
  sonarqube-analysis:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Set up SonarQube Scanner
      run: |
        echo "D:\\sonar-scanner-4.0.0.1744-windows\\bin" >> $env:Path
        
    - name: SonarQube Scan
      run: |
        # Run SonarQube analysis
        cmd /c "D:\\sonar-scanner-4.0.0.1744-windows\\bin\\sonar-scanner.bat" ^
          -Dsonar.host.url=https://5746-103-81-78-10.ngrok-free.app ^
          -Dsonar.login=$SONAR_TOKEN ^
          -Dsonar.projectKey=sonar_git_yml:master ^
          -Dsonar.projectName=sonar_git_yml:master ^
          -Dsonar.sources=.
